### ISSUE TITLE
json unmarshal error from ListIssueEventsForRepository

### ISSUE THREAD

**Issue by kylebrandt** [google/go-github#176]
Maybe I'm doing something wrong?

```
package main

import (
    "fmt"

    "github.com/google/go-github/github"

    "code.google.com/p/goauth2/oauth"
)

func main() {
    t := &oauth.Transport{
        Token: &oauth.Token{AccessToken: "..."},
    }
    client := github.NewClient(t.Client())
    issues, r, err := client.Activity.ListIssueEventsForRepository("bosun-monitor", "bosun", &github.ListOptions{Page: 1, PerPage: 20})
    fmt.Println(r.Status)
    if err != nil {
        panic(err)
    }
    fmt.Println(issues)
}
```

Returns:

```
    200 OK
    panic: json: cannot unmarshal number into Go value of type string

    goroutine 1 [running]:
    main.main()
        /Users/kbrandt/src/github.go:19 +0x2f3

    goroutine 9 [runnable]:
    net/http.(*persistConn).readLoop(0xc208060000)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:928 +0x9ce
    created by net/http.(*Transport).dialConn
        /usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:660 +0xc9f

    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
        /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1

    goroutine 10 [select]:
    net/http.(*persistConn).writeLoop(0xc208060000)
        /usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:945 +0x41d
    created by net/http.(*Transport).dialConn
        /usr/local/Cellar/go/1.4/libexec/src/net/http/transport.go:661 +0xcbc
    exit status 2

    exit status 1
```

**Comment by yisiper** [comment]
The API and library doesn't match.
https://github.com/google/go-github/blob/master/github/activity_events.go#L153

```
// GitHub API docs: http://developer.github.com/v3/activity/events/#list-issue-events-for-a-repository
func (s *ActivityService) ListIssueEventsForRepository(owner, repo string, opt *ListOptions) ([]Event, *Response, error) {
	u := fmt.Sprintf("repos/%v/%v/issues/events", owner, repo)
	u, err := addOptions(u, opt)
	if err != nil {
		return nil, nil, err
	}
```

if you want this API
https://developer.github.com/v3/issues/events/#list-events-for-a-repository
try use this ``` Issues.ListRepositoryEvents ```
https://github.com/google/go-github/blob/master/github/issues_events.go#L88

**Comment by shurcooL** [comment]
@kylebrandt Looks like this was a valid bug in the library, which should be fixed soon thanks to a PR by @whilp. My https://github.com/google/go-github/pull/475#pullrequestreview-10113028 describes the details of how it happened.
